# the image should be ran with 1GPU, 12 cores, 64 gb, NVIDIA a100-80gb

# Start from the NVIDIA CUDA 12.3.1 development image based on Ubuntu 22.04
FROM nvidia/cuda:12.3.1-devel-ubuntu22.04

# Set noninteractive to avoid prompts during package installation
ARG DEBIAN_FRONTEND=noninteractive

# Install Python and pip
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3.10 \
    python3-pip \
    python3-dev && \
    # Clean up
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Make python3 and pip3 the default commands
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1 && \
    update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

WORKDIR /srv
USER root

RUN apt-get update --yes && \
    apt-get upgrade --yes && \
    apt-get install --yes --no-install-recommends  git wget curl

RUN pip install fschat scipy
RUN pip install fschat[model_worker,webui] pydantic==1.10.13
RUN pip install langchain openai chromadb

# docker build ./jhub/images/LLM -f ./jhub/images/LLM/Dockerfile_llm_backend -t gitlab-registry.nrp-nautilus.io/ndp/ndp-docker-images/llm_backend:v0.0.0.1 --platform=linux/amd64