# Notes:
# NDP Test Nautilus namespace: ndp-test
# Install client-secret k8s secret (need to insert it in the file ndp-hub/my_secret.yaml): kubectl create secret generic jupyterhub-secret --from-file=values.yaml=ndp-hub/my_secret.yaml -n ndp-test
# Install from ./helm folder: helm upgrade --cleanup-on-fail --install ndp-hub ndp-hub --kube-context nautilus --namespace ndp-test --values ndp-hub/values_test.yaml
# Uninstall: helm uninstall ndp-hub --kube-context nautilus --namespace ndp-test
# URL: ndp-test-jupyterhub.nrp-nautilus.io

jupyterhub:
  hub:
    image:
      name: gitlab-registry.nrp-nautilus.io/ndp/ndp-docker-images/jh
      tag: "2.0.11"
    extraEnv:
      JUPYTERHUB_METRICS_API_KEY:
        valueFrom:
          secretKeyRef:
            name: jupyterhub-metrics-secret
            key: metrics-api-key
    existingSecret: jupyterhub-secret
    config:
      GenericOAuthenticator:
        oauth_callback_url: http://localhost:8080/hub/oauth_callback  # <-- LOCAL callback URL
        authorize_url: https://idp-test.nationaldataplatform.org/realms/NDP/protocol/openid-connect/auth
        token_url: https://idp-test.nationaldataplatform.org/realms/NDP/protocol/openid-connect/token
        userdata_url: https://idp-test.nationaldataplatform.org/realms/NDP/protocol/openid-connect/userinfo
        logout_redirect_url: https://idp-test.nationaldataplatform.org/realms/NDP/protocol/openid-connect/logout?redirect_uri=http://localhost:8080
        login_service: keycloak
        username_claim: preferred_username
        userdata_params:
          state: state
        allow_all: False
        allowed_groups: ["jhub_user", "/jhub_user"]
        auto_login: True
        enable_auth_state: True
        admin_users: [ "" ]
        scope:
          - openid
          - profile
      JupyterHub:
        authenticator_class: generic-oauth
    service:
      type: ClusterIP
      annotations: {}
      ports:
        nodePort:
      loadBalancerIP:
    deploymentStrategy:
      type: Recreate
    db:
      type: sqlite-pvc
      pvc:
        accessModes:
          - ReadWriteOnce
        storage: 512Mi
        storageClassName: standard
    resources:
      limits:
        cpu: "1"
        memory: 1G
      requests:
        cpu: 100m
        memory: 512M
    networkPolicy:
      enabled: false
# Commenting this out because new hub docker image has templates and pics inside it
#    initContainers:
#      - name: git-clone-templates
#        image: alpine/git
#        args:
#          - clone
#          - --single-branch
#          - --branch=main
#          - --depth=1
#          - --
#          - https://github.com/national-data-platform/jupyter-templates.git
#          - /etc/jupyterhub/custom
#        securityContext:
#          runAsUser: 0
#        volumeMounts:
#          - name: custom-templates
#            mountPath: /etc/jupyterhub/custom
#    extraVolumes:
#      - name: custom-templates
#        emptyDir: { }
#    extraVolumeMounts:
#      - name: custom-templates
#        mountPath: /etc/jupyterhub/custom
    extraConfig:

      default.py: |
# spawner_local.py code here

  # proxy:
  #   secretToken: ""  # Generate with: openssl rand -hex 32
  #   service:
  #     type: ClusterIP
  #   chp:
  #     resources:
  #       limits:
  #         cpu: "1"
  #         memory: 1Gi
  #       requests:
  #         cpu: 200m
  #         memory: 512Mi

  proxy:
    service:
      type: NodePort
      nodePorts:
        http: 30080

  singleuser:
    uid: 1000
    fsGid: 100
    allowPrivilegeEscalation: true
    extraPodConfig:
      securityContext:
          fsGroupChangePolicy: "OnRootMismatch"
    cloudMetadata:
      blockWithIptables: false
    networkPolicy:
      enabled: false
    initContainers:
    - name: volume-permissions
      image: busybox
      command: ["sh", "-c", "chmod 777 -R /home/jovyan/work/_User-Persistent-Storage_CephBlock_"]
      volumeMounts:
        - mountPath: /home/jovyan/work/_User-Persistent-Storage_CephBlock_
          name: volume-ceph-bw-{username}
    storage:
      extraLabels: {}
      capacity: 2Gi
      homeMountPath: /home/jovyan/work/_User-Persistent-Storage_CephBlock_
      dynamic:
        storageClass: standard
        pvcNameTemplate: claim-ceph-bw-{username}
        volumeNameTemplate: volume-ceph-bw-{username}
        storageAccessModes: [ReadWriteOnce]

    image:
      name: gitlab-registry.nrp-nautilus.io/ndp/ndp-docker-images/jhub-spawn
      tag: minimal_0.0.10
    startTimeout: 300
    cpu:
      limit: 1
      guarantee: 1
    memory:
      limit: 2G
      guarantee: 
    extraResource:
      limits: {}
      guarantees: {}
    cmd: jupyterhub-singleuser
    defaultUrl: "/lab"

  scheduling:
    userScheduler:
      enabled: false
    userPlaceholder:
      enabled: false
  # prePuller relates to the hook|continuous-image-puller DaemonsSets
  prePuller:
    hook:
      enabled: false
    continuous:
      enabled: false

  # ingress:
  #   enabled: true
  #   annotations:
  #     kubernetes.io/ingress.class: haproxy
  #   hosts: ["ndp-test-jupyterhub.nrp-nautilus.io"]
  #   pathSuffix: ''
  #   tls:
  #     - hosts:
  #       - ndp-test-jupyterhub.nrp-nautilus.io
  ingress:
    enabled: false

  cull:
    enabled: true
    users: false
    removeNamedServers: false
    timeout: 3600
    every: 600
    concurrency: 10
    maxAge: 0