apiVersion: v1
kind: ServiceAccount
metadata:
  name: jhub-api-culler
  namespace: ndp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jhub-api-culler-role
  namespace: ndp
rules:
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jhub-api-culler-rolebinding
  namespace: ndp
subjects:
  - kind: ServiceAccount
    name: jhub-api-culler
    namespace: ndp
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: jhub-api-culler-role