FROM jupyterhub/k8s-hub:2.0.0
#LABEL authors="sergeygurvich"

#USER root

#RUN mkdir -p /templates
#COPY templates/* /templates/

COPY images/ndp_logo.png /usr/local/share/jupyterhub/static/images/ndp_logo.png

#USER jovyan