FROM rocker/binder:latest

USER root

# Install system packages
RUN apt-get update && apt-get install -y \
    git \
    sudo \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Allow jovyan passwordless sudo
RUN echo 'jovyan ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

# Install Python packages
RUN pip install requests \
    && pip install jupyterlab==4.2.4


WORKDIR /home/jovyan/work

USER jovyan

#docker build ./images -f ./images/Dockerfile_rstudio_binder -t gitlab-registry.nrp-nautilus.io/ndp/ndp-docker-images/jhub-spawn:rstudio_v0.0.1 --platform=linux/amd64 --no-cache