FROM rocker/rstudio:4.3.1

USER root

# Install system dependencies and Python packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    python3-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    git && \
    pip3 install --no-cache-dir \
    jupyterlab==4.2.4 \
    jupyter-rsession-proxy \
    requests && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Ensure R config dir writable
RUN chmod -R u+w /usr/local/lib/R/etc

# Allow rstudio user to sudo without password
RUN echo 'rstudio ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/rstudio && \
    chmod 0440 /etc/sudoers.d/rstudio

# Create workspace directory and set ownership
RUN mkdir -p /home/jovyan/work && \
    chown -R rstudio:rstudio /home/jovyan

# Set working directory
WORKDIR /home/jovyan/work

# Set default password for RStudio Server login
ENV PASSWORD=ndpRstudio2025
RUN echo "rstudio:${PASSWORD}" | chpasswd

ENV TERM=xterm

USER rstudio

#docker build ./images -f ./images/Dockerfile_rstudio -t gitlab-registry.nrp-nautilus.io/ndp/ndp-docker-images/jhub-spawn:rstudio_v0.0.1 --platform=linux/amd64 --no-cache