FROM quay.io/jupyter/base-notebook:latest

WORKDIR /home/jovyan/work

USER root

RUN apt-get update && apt-get install -y \
    git

RUN chmod a+x /usr/bin/git

RUN git clone https://github.com/national-data-platform/jupyter-notebooks

RUN pip install -r ./jupyter-notebooks/minimal_starter_content/requirements.txt

RUN cp -R ./jupyter-notebooks/minimal_starter_content/. .
RUN rm -rf ./jupyter-notebooks

# make sudo access without password
RUN echo 'jovyan ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

RUN chown -R jovyan ./

USER jovyan

# docker build ./images -f ./images/Dockerfile_cat_search -t gitlab-registry.nrp-nautilus.io/ndp/ndp-docker-images/jhub-spawn:catalog_search_v0.7 --platform=linux/amd64 --no-cache