FROM quay.io/jupyter/base-notebook:latest

WORKDIR /home/jovyan/work

USER root

RUN apt-get update && apt-get install -y \
    git

RUN git clone https://github.com/national-data-platform/jupyter-notebooks

RUN pip install -r ./jupyter-notebooks/earthscope/requirements.txt

RUN cp -R ./jupyter-notebooks/earthscope/. .
RUN rm -rf ./jupyter-notebooks

USER jovyan

# docker build ./images -f ./images/Dockerfile_earthscope -t gitlab-registry.nrp-nautilus.io/ndp/ndp-docker-images/jhub-spawn:earthscope_v0.2.4.3 --platform=linux/amd64 --no-cache