FROM quay.io/jupyter/base-notebook:latest

WORKDIR /home/jovyan/work

USER root

RUN apt-get update && apt-get install -y \
    git

RUN git clone https://github.com/national-data-platform/jupyter-notebooks

RUN pip install jupyterlab-git ndp-jupyterlab-extension==0.1.55 --index-url https://gitlab.nrp-nautilus.io/api/v4/projects/4145/packages/pypi/simple
RUN pip install -r ./jupyter-notebooks/sage/requirements.txt

RUN cp -R ./jupyter-notebooks/sage/. .
RUN rm -rf ./jupyter-notebooks

RUN chown -R jovyan /home/jovyan

USER jovyan

# docker build ./images -f ./images/Dockerfile_sage -t gitlab-registry.nrp-nautilus.io/ndp/ndp-docker-images/jhub-spawn:sage_v0.2.1.4 --platform=linux/amd64 --no-cache