FROM quay.io/jupyter/base-notebook:latest

WORKDIR /home/jovyan/work

USER root

RUN apt-get update && apt-get install -y \
    git

RUN git clone https://github.com/national-data-platform/jupyter-notebooks

# M1 support
ARG TARGETPLATFORM
RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then conda install -y gcc gxx_linux-64; fi

RUN pip install -r ./jupyter-notebooks/pgml/requirements.txt

RUN cp -R ./jupyter-notebooks/pgml/. .
RUN rm -rf ./jupyter-notebooks

RUN chown -R jovyan ./
USER jovyan

# docker build ./images -f ./images/Dockerfile_pgml -t gitlab-registry.nrp-nautilus.io/ndp/ndp-docker-images/jhub-spawn:pgml_v0.1.7.3 --platform=linux/amd64 --no-cache