FROM quay.io/jupyter/base-notebook:latest

WORKDIR /srv

USER root

RUN apt-get update && apt-get install -y \
    git

RUN git clone https://github.com/national-data-platform/jupyter-notebooks

RUN pip install -r /srv/jupyter-notebooks/earthscope/requirements.txt

RUN mkdir /srv/starter_content/

RUN cp -R /srv/jupyter-notebooks/earthscope/. /srv/starter_content/

RUN chown -R jovyan /srv/starter_content/

USER jovyan

# docker build ./jhub/images -f ./jhub/images/Dockerfile_earthscope -t gitlab-registry.nrp-nautilus.io/ndp/ndp-docker-images/jhub-spawn:earthscope_v0.2.1.0 --platform=linux/amd64 --no-cache