FROM quay.io/jupyter/base-notebook:latest

WORKDIR /srv

USER root

RUN apt-get update && apt-get install -y \
    git

RUN git clone https://github.com/national-data-platform/jupyter-notebooks

# M1 support
ARG TARGETPLATFORM
RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then conda install -y gcc gxx_linux-64; fi

RUN pip install -r /srv/jupyter-notebooks/pgml/requirements.txt

RUN mkdir /srv/starter_content/

RUN cp -R /srv/jupyter-notebooks/pgml/. /srv/starter_content/

RUN chown -R jovyan /srv/starter_content/

USER jovyan

# docker build ./jhub/images -f ./jhub/images/Dockerfile_pgml -t gitlab-registry.nrp-nautilus.io/ndp/ndp-docker-images/jhub-spawn:pgml_v0.1.7.1 --platform=linux/amd64 --no-cache