FROM quay.io/jupyter/base-notebook:latest

WORKDIR /home/jovyan/work

USER root

RUN apt-get update && apt-get install -y \
    git

RUN git clone https://github.com/national-data-platform/jupyter-notebooks

RUN pip install -r ./jupyter-notebooks/nasa/requirements.txt

RUN cp -R ./jupyter-notebooks/nasa/. .
RUN rm -rf ./jupyter-notebooks

RUN chown -R jovyan ./

USER jovyan

# docker build ./images -f ./images/Dockerfile_nasa -t gitlab-registry.nrp-nautilus.io/ndp/ndp-docker-images/jhub-spawn:nasa_v0.1.0.0 --platform=linux/amd64 --no-cache